<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Source+Code+Pro" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300" rel="stylesheet">
 	<link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
 	<link rel="stylesheet" type="text/css" href="second-style.css">
  <link rel="stylesheet" type="text/css" href="pp.css">
	<title>Shop - Sneakers</title>
</head>
<body id="sneakers-body">
	<div class="Title">
		<a href="index.html" class="arrow-left"><i class="fas fa-angle-left"></i></a>
		<h1>Sneakers</h1>
		<div class="social-container colwhi">
	        <a target="_blank" href="https://www.facebook.com/eyoooooooooooo"><i class="soc-icon fab fa-facebook-f"></i></a>
	        <a target="_blank" href="https://www.instagram.com/kirvoksas/"><i class="soc-icon fab fa-instagram"></i></a>
	        <a target="_blank" href="https://twitter.com/Daniilas_I"><i class="soc-icon fab fa-twitter"></i></a>
	        <a target="_blank" href="https://www.google.com/"><i class="soc-icon fab fa-google"></i></a>
          <div class="menu">
            <button class="nav-tgl" type="button" aria-label="toggle menu">
              <!-- this span just for the three dividers in the hamburger button--><span aria-hidden="true"></span>
            </button>
            <nav class="nav">
              <ul class="list">
                <li>Sandals</li>
                <li>Skateboarding</li>
                <li>Classic</li>
              </ul>
            </nav>
          </div>
        </div>
    </div>
   	<main>
   		<div class="main-text">
   			<h2>Choose yours</h2>
   			<p>
   				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nibh purus, fringilla a feugiat eu, commodo nec tortor. Duis mi nunc, pharetra sed dignissim nec, tempor at enim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum quis nulla cursus, placerat ipsum ac, interdum metus. Suspendisse potenti. Aenean tempus efficitur posuere. Proin dignissim, eros nec aliquet dictum, eros turpis pulvinar neque, vel posuere turpis nunc placerat velit. Curabitur tempor velit augue. Fusce eget nisi ut sem varius tincidunt eget eget ligula. Cras eget blandit ex. In eleifend porta orci, sit amet rutrum odio iaculis ac. Proin posuere odio non nisi euismod, eu mattis mauris auctor. In quis pulvinar eros.
   			</p>
   		</div>
   		<div class="shop-main">
        <div class="shop-topbar">
          <div>
            
          </div>
        </div>
        <div class="shop-sidebar">
          
        </div>
      </div>
   	</main>
    <script type="text/javascript" src="menu-popup.js"></script>
</body>
</html>