<?php
  $productsFromJson = file_get_contents('ddd.json');
  $productsArray = json_decode($productsFromJson, true);
  $productsArray = $productsArray['products'];
?>
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Source+Code+Pro" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300" rel="stylesheet">
 	<link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
 	<link rel="stylesheet" type="text/css" href="second-style.css">
  <link rel="stylesheet" type="text/css" href="pp.css">
	<title>Shop - Sneakers</title>
</head>
<body id="sneakers-body">
	<div class="Title">
		<a href="index.html" class="arrow-left"><i class="fas fa-angle-left"></i></a>
		<h1>Sneakers</h1>
		<div class="social-container colwhi">
	       <a target="_blank" href="https://www.facebook.com/eyoooooooooooo"><i class="soc-icon fab fa-facebook-f"></i></a>
	       <a target="_blank" href="https://www.instagram.com/kirvoksas/"><i class="soc-icon fab fa-instagram"></i></a>
	       <a target="_blank" href="https://twitter.com/Daniilas_I"><i class="soc-icon fab fa-twitter"></i></a>
	       <a target="_blank" href="https://www.google.com/"><i class="soc-icon fab fa-google"></i></a>
        <div class="menu">
          <button class="nav-tgl" type="button" aria-label="toggle menu">
            <span aria-hidden="true"></span>
          </button>
          <nav class="nav">
          </nav>
        </div>
    </div>
  </div>

  <!-- HIDDEN -->

  <div class="list-box">
    <ul class="list">
      <li>Sandals</li>         
      <li>Skateboarding</li>
      <li>Classic</li>
    </ul>
  </div>

  <main>
   	<div class="shop-main">
      <div class="shop-topbar">
        <div>
            
        </div>
      </div>
      <div class="shop-sidebar">
          <ul class="sidebar-list">
            <li class="sidebar-list-header">Brands</li>
              <ul class="sidebar-list-items">
                <li>Adidas</li>
                <li>Nike</li>
                <li>Balenciaga</li>
                <li>Off White </li>
              </ul>
          </ul>
     </div>
     <div class="shop-main-items">
       <?php foreach ($productsArray as $product): ?>
         <div class="item">
            <div class="item-image" style="background-image: url(<?= $product['image'];?>)">
      
            </div>
            <p class="item-name"><?= $product['name'];?></p>
            <p class="item-descripion"><?= $product['description']; ?></p>
          </div>
        <?php endforeach; ?>
     </div>
    </div>
  </main>
  <script type="text/javascript" src="menu-popup.js"></script>
</body>
</html>
