<?php
	$productsFromJson = file_get_contents('ddd.json');
	$productsArray = json_decode($productsFromJson, true);
	$productsArray = $productsArray['products'];
?>
<!DOCTYPE html>
<html>
<head>
	<title>sss</title>
	<style type="text/css">
		body{
			width: 100%;
			height: 100vh;
			margin: 0;
			padding: 0;
		}
		.cont{
			display: block;
			border: 2px black solid;
			width: 50%;
			height: 50vh;
		}
		.image-div{
			width: 80%;
			height: 20vh;
			margin: 0 auto;
		}
	</style>
</head>
<body>
	<?php foreach ($productsArray as $product): ?>
	<div class="cont">
		<div class="image-div" style="background-image: url(<?= $product['image'];?>)">
			
		</div>
		<p><?= $product['name'];?></p>
		<p><?= $product['description']; ?></p>
	</div>
	<?php endforeach; ?>
</body>
</html>
